---

- hosts: tag_Name_bastion-1-public
sudo: yes
gather_facts: no
remote_user: ubuntu

tasks:
  - name:install fail2ban
    apt: name=fail2ban state=lates
    
  - name: install sendmail
    apt: name=sendmail state=latest
